site_name: ProArc - uživatelská dokumentace
site_url: https://mydomain.org/mysite
theme:
  logo: images/logo-proarc-7.svg
  favicon: images/favicon.ico
  name: material
  language: cs
  font:
    text: Roboto
    code: Red Hat Mono
  palette: 
  # toggle pro light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Přepnout na tmavý režim
    # toggle pro dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Přenost na světlý režim
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.top
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/proarc/proarc-client/wiki
      name: ProArc na GitHubu
  status:
    new: Nově přidáno
    old: Zastaralé
copyright: Copyright &copy; 2025 Knihovna Akademie věd ČR, v. v. i.

nav:
  - Úvod:
      - Obsah: index.md
      - O systému ProArc: o_proarcu.md
      - Historie projektu a financování: historie_projektu_a_financovani.md
      - Kontakt: kontakt.md
      - Chybí něco v návodu?: chybi_neco_v_navodu.md
  - Základní přehled:
      - Přihlášení a navigace: zakladni_prehled/01_prihlaseni.md
      - Obrazovka úložiště: zakladni_prehled/02_uloziste.md
      - Import a Správa procesů: zakladni_prehled/03_import.md
      - Zařízení: zakladni_prehled/04_zarizeni.md
      - Administrace: zakladni_prehled/05_administrace.md
      - O aplikaci: zakladni_prehled/06_oAplikaci.md
      - Profil: zakladni_prehled/07_profil.md
      - Nastavení jazyka: zakladni_prehled/08_jazyk.md
  - Typy dokumentů: 
      - Přehled dokumentů: jak_zpracovat_dokument/typy_dokumentu.md
      - Postup zpracování konkrétních typů dokumentů:
        - Monografie: jak_zpracovat_dokument/monografie.md
        - Vícesvazková monografie: jak_zpracovat_dokument/vicesvazkova_monografie.md
        - Periodika: jak_zpracovat_dokument/periodika.md
        - E-monografie: jak_zpracovat_dokument/e_monografie.md
        - Vícesvazková E-monografie: jak_zpracovat_dokument/vicesvazkova_e_monografie.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  